#!/bin/sh

OUTFILE=`echo $1 | sed -e 's/\.hkl$/.mtz/'`

#echo " Input: $1"
#echo "Output: $OUTFILE"

sed -n '/End\ of\ reflections/q;p' $1 > create-mtz.temp.hkl

#echo "Running 'f2mtz'..."
f2mtz HKLIN create-mtz.temp.hkl HKLOUT $OUTFILE > out.html << EOF
TITLE Reflections from CrystFEL
NAME PROJECT wibble CRYSTAL wibble DATASET wibble
CELL 66.9 66.9 40.8  90  90 120
SYMM P63
SKIP 3
LABOUT H K L IMEAN SIGIMEAN
CTYPE  H H H J     Q
FORMAT '(F5.0,1X,2(F4.0,1X),F11.2,1X,F11.2)'
EOF

if [ $? -ne 0 ]; then echo "Failed."; exit; fi

rm -f create-mtz.temp.hkl
echo "Done."
